package swag

import (
  "PapayaNet/papaya/koala"
  m "PapayaNet/papaya/koala/mapping"
  "strings"
)

// normalize path

func SwagPathNorm(p string) string {

  res := make([]string, 0)
  tokens := strings.Split(p, "/")

  for _, token := range tokens {

    k := len(token)

    if k > 0 {

      if koala.KStrHasPrefixChar(token, ":") {

        res = append(res, "{"+token[1:]+"}")
        continue
      }
    }

    res = append(res, token)
  }

  return strings.Join(res, "/")
}

// short function

func OkJSON(data any) m.KMapImpl {

  return &m.KMap{
    "200": &m.KMap{
      "body": JSON(data),
    },
  }
}

// Created

func CreatedJSON(data any) m.KMapImpl {

  return &m.KMap{
    "201": &m.KMap{
      "body": JSON(data),
    },
  }
}

// passing description, auto generated by http.StatusText(code int)

func JSON(data any) m.KMapImpl {

  return &m.KMap{
    "application/json": &m.KMap{
      "schema": data,
    },
  }
}
